[book]
title = "The Romanian Language"
authors = ["Dorian Oszczęda"]
description = "Resources to learn the Romanian language and its dialects"
language = "en"

[preprocessor.pagetoc]

[output.html]
default-theme = "Ayu"
smart-punctuation = true
git-repository-url = "https://github.com/vxern/romanian"
edit-url-template = "https://github.com/vxern/romanian/edit/main/{path}"
additional-js = ["theme/pagetoc.js"]
additional-css = ["theme/pagetoc.css", "theme/width-override.css"]

[output.html.fold]
enable = false
